### PR TITLE
Allow multiple chainings of rule groups

### PR DESCRIPTION
**Pull request by ryanpiaskowy**
Even though the rules maintenance UI does not allow multiple chaining of rule groups (ie group 4 depends on group 3 which depends on group 2 which depends on group 1), it is possible to achieve this in the database. The UI subsequently displays both the tree icon and the chain icon indicated a group is dependent on it and it depends on another group. This update to the underlying rules engine will accommodate this multiple chaining. 

- Changed the RuleGroupPrioritizer to add groups to the prioritized array in the order of dependence (in the above example, rule group 1 would always be executed first).
- Changed the BusinessRulesEngine to skip a rule if the depedending rule was skipped to stop the chain as soon as one link broke.

The jar I exported from the project works with the Pentaho plugin as expected; however, appears to be much larger than the original. If you could re-compile it using your method to reduce the size of the jar, that would be great.

Thanks,
Ryan

Below is a screenshot of what the rules maintenance UI looks like when chaining rules:
screen shot 2018-03-08 at 2 45 42 pm

### CODE REVIEW

**Comment by ryanpiaskowy** [comment]
I also adding the ignore case option to CheckNotContains

**Comment by uwegeercken** [comment]
Sorry for late reply. I will have a look at this the next days (I hope).

On thing I have to check is what happens if one of the groups in the chain expire (validity date).

The other thing I do not understand is, that you say that the change can be done in the database - but the UI will have to be adjusted as well I guess.

And I have a separate request to allow enabling/disabling of groups in the UI, so that will have to fit too somehow.

**Comment by uwegeercken** [comment]
two more items to watch out: circular references of rulegroups have to be avoided. and the ui will have to be adjusted to allow chaining of multiple groups. did you have a look at that?

**Comment by uwegeercken** [comment]
too old. no feedback anymore

**Pull request closed without merging**
